# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18', '1.19', '1.20' ]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Format
      run: make fmt

    - name: Build
      run: make build

    - name: Test
      run: go test -json -v -coverpkg=./... -coverprofile=TestCoverage-${{ matrix.go-version }}.out ./... > TestResults-${{ matrix.go-version }}.json

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.go-version }}
        path: TestResults-${{ matrix.go-version }}.json

    - name: Upload test coverage
      uses: actions/upload-artifact@v3
      with:
        name: test-coverage-${{ matrix.go-version }}
        path: TestCoverage-${{ matrix.go-version }}.out
